import { db } from "./index";
import { vehicles, reviews, leads, testDrives, appraisals } from "./schema";
import { count } from "drizzle-orm";

export const initialVehicles = [
  {
    brand: "Fiat",
    model: "Argo",
    version: "1.3 Firefly Drive",
    yearFabrication: 2021,
    yearModel: 2021,
    price: "65900.00",
    fipePrice: "68200.00",
    mileage: 32000,
    fuel: "Flex",
    transmission: "Manual",
    color: "Prata",
    bodyType: "Hatch",
    plateEnd: "4",
    doors: 4,
    coverImage: "/images/vehicles/fiat-argo.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/fiat-argo.jpg"
    ]),
    features: JSON.stringify([
      "Ar-condicionado",
      "Direção elétrica progressiva",
      "Central multimídia 7\" com Apple CarPlay e Android Auto",
      "Vidros elétricos dianteiros",
      "Travas elétricas",
      "Sensor de estacionamento traseiro",
      "Computador de bordo",
      "Volante multifuncional com regulagem de altura",
      "Airbag duplo",
      "Freios ABS com EBD",
      "Controle de tração e estabilidade"
    ]),
    description: "Fiat Argo 1.3 Drive com motor Firefly super econômico e ágil para o dia a dia em Juiz de Fora. Veículo em excelente estado de conservação, com apenas 32.000 km rodados, todas as revisões em dia com manual e chave reserva. Pneus novos e interior higienizado. Laudo cautelar 100% aprovado.",
    isFeatured: true,
    badge: "Único Dono",
    hasInspectionReport: true,
    singleOwner: true,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Volkswagen",
    model: "Gol",
    version: "1.6 MSI 8V TotalFlex",
    yearFabrication: 2020,
    yearModel: 2020,
    price: "54900.00",
    fipePrice: "56800.00",
    mileage: 45000,
    fuel: "Flex",
    transmission: "Manual",
    color: "Branco",
    bodyType: "Hatch",
    plateEnd: "8",
    doors: 4,
    coverImage: "/images/vehicles/vw-gol.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/vw-gol.jpg"
    ]),
    features: JSON.stringify([
      "Ar-condicionado gelando",
      "Direção hidráulica",
      "Vidros elétricos dianteiros",
      "Travas elétricas com acionamento na chave",
      "Som com Bluetooth e USB",
      "Airbag duplo",
      "Freios ABS",
      "Desembaçador e limpador traseiro",
      "Alarme perimétrico"
    ]),
    description: "Gol 1.6 MSI completinho, robustez mecânica comprovada e manutenção extremamente barata. Ótimo custo-benefício para quem procura um carro confiável para trabalho ou família. Laudo pericial aprovado sem restrições.",
    isFeatured: false,
    badge: "Seminovo",
    hasInspectionReport: true,
    singleOwner: false,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Chevrolet",
    model: "Onix",
    version: "1.0 Turbo LT Automático",
    yearFabrication: 2022,
    yearModel: 2022,
    price: "78900.00",
    fipePrice: "81500.00",
    mileage: 22000,
    fuel: "Flex",
    transmission: "Automático",
    color: "Vermelho",
    bodyType: "Hatch",
    plateEnd: "2",
    doors: 4,
    coverImage: "/images/vehicles/chevrolet-onix.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/chevrolet-onix.jpg"
    ]),
    features: JSON.stringify([
      "Câmbio automático de 6 marchas",
      "6 Airbags (frontais, laterais e de cortina)",
      "Controle eletrônico de estabilidade e tração",
      "Assistente de partida em rampa (HSA)",
      "Central MyLink 8\" com Wi-Fi nativo e OnStar",
      "Câmera de ré de alta resolução",
      "Sensor de estacionamento",
      "Rodas de liga leve aro 15\"",
      "Chave canivete com abertura remota",
      "Volante multifuncional em couro"
    ]),
    description: "Onix Turbo LT Automático em estado de 0km! Apenas 22.000 km, garantia de procedência, econômico e potente com motor turbo 116cv. Carro sem nenhum detalhe na pintura, interior sem desgastes.",
    isFeatured: true,
    badge: "Destaque",
    hasInspectionReport: true,
    singleOwner: true,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Jeep",
    model: "Renegade",
    version: "1.8 Flex Sport Automático",
    yearFabrication: 2021,
    yearModel: 2021,
    price: "94900.00",
    fipePrice: "97300.00",
    mileage: 38000,
    fuel: "Flex",
    transmission: "Automático",
    color: "Preto",
    bodyType: "SUV",
    plateEnd: "6",
    doors: 4,
    coverImage: "/images/vehicles/jeep-renegade.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/jeep-renegade.jpg"
    ]),
    features: JSON.stringify([
      "Câmbio automático de 6 marchas com modo Sport",
      "Bancos revestidos em couro nobre",
      "Central Multimídia Uconnect de 7\" com espelhamento",
      "Câmera de ré com linhas dinâmicas",
      "Controle de tração e estabilidade com sistema anti-capotamento",
      "Faróis com assinatura em LED e DRL",
      "Rodas de liga leve aro 17\"",
      "Piloto automático e limitador de velocidade",
      "Freio de estacionamento eletrônico"
    ]),
    description: "Jeep Renegade Sport Automático impecável! Conforto, posição alta de dirigir e imponência pelas ruas de Juiz de Fora. Equipado com bancos de couro originais, revisado recentemente e com 4 pneus Pirelli em excelente estado.",
    isFeatured: true,
    badge: "Oportunidade",
    hasInspectionReport: true,
    singleOwner: false,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Honda",
    model: "Civic",
    version: "2.0 16V EXL CVT",
    yearFabrication: 2019,
    yearModel: 2020,
    price: "105900.00",
    fipePrice: "109800.00",
    mileage: 55000,
    fuel: "Flex",
    transmission: "CVT",
    color: "Prata",
    bodyType: "Sedan",
    plateEnd: "9",
    doors: 4,
    coverImage: "/images/vehicles/honda-civic.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/honda-civic.jpg"
    ]),
    features: JSON.stringify([
      "Câmbio automático CVT de 7 marchas simuladas com Paddle Shift",
      "Bancos em couro legítimo preto",
      "Painel de instrumentos 100% digital em TFT de 7\"",
      "Ar-condicionado digital Dual Zone",
      "Faróis Full LED com acendimento automático",
      "Central Multimídia 7\" com GPS integrado",
      "Freio de estacionamento eletrônico com função Brake Hold",
      "Câmera de ré multi-ângulo e sensores dianteiros/traseiros",
      "Rodas diamantadas aro 17\"",
      "6 Airbags e estrutura com tecnologia ACE"
    ]),
    description: "O mais desejado sedan médio do mercado! Honda Civic G10 EXL 2.0 completíssimo, design atemporal, estabilidade inigualável e revenda garantida. Carro extremamente cuidado por entusiasta, histórico completo na concessionária.",
    isFeatured: true,
    badge: "Destaque",
    hasInspectionReport: true,
    singleOwner: true,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Toyota",
    model: "Corolla",
    version: "2.0 XEi Direct Shift",
    yearFabrication: 2020,
    yearModel: 2021,
    price: "115900.00",
    fipePrice: "119500.00",
    mileage: 41000,
    fuel: "Flex",
    transmission: "CVT",
    color: "Branco Perolizado",
    bodyType: "Sedan",
    plateEnd: "1",
    doors: 4,
    coverImage: "/images/vehicles/toyota-corolla.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/toyota-corolla.jpg"
    ]),
    features: JSON.stringify([
      "Motor 2.0 Dynamic Force de 177cv",
      "Câmbio Direct Shift de 10 marchas com 1ª mecânica",
      "Toyota Safety Sense (frenagem autônoma de emergência)",
      "Piloto automático adaptativo (ACC)",
      "Alerta de mudança involuntária de faixa",
      "Farol alto automático",
      "Chave presencial Smart Entry e botão Start/Stop",
      "Ar-condicionado automático digital",
      "Central Multimídia Toyota Play 8\" com Apple CarPlay",
      "7 Airbags (incluindo joelho para o motorista)"
    ]),
    description: "Toyota Corolla XEi 2.0 da nova geração na clássica e valorizada cor Branco Perolizado. O símbolo máximo de confiabilidade, segurança com pacote Toyota Safety Sense e economia surpreendente na estrada.",
    isFeatured: true,
    badge: "Garantia",
    hasInspectionReport: true,
    singleOwner: true,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Hyundai",
    model: "HB20",
    version: "1.0 TGDI Comfort Automático",
    yearFabrication: 2022,
    yearModel: 2023,
    price: "67900.00",
    fipePrice: "71000.00",
    mileage: 18000,
    fuel: "Flex",
    transmission: "Automático",
    color: "Azul Sapphire",
    bodyType: "Hatch",
    plateEnd: "5",
    doors: 4,
    coverImage: "/images/vehicles/hyundai-hb20.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/hyundai-hb20.jpg"
    ]),
    features: JSON.stringify([
      "Motor 1.0 Turbo GDI de 120cv",
      "Câmbio automático de 6 marchas",
      "Central multimídia de 8\" BlueMedia sem fio",
      "Direção elétrica progressiva",
      "Controle de tração e estabilidade",
      "Assistente de partida em rampa",
      "6 Airbags de série",
      "Piloto automático e limitador de velocidade",
      "Vidros elétricos nas 4 portas"
    ]),
    description: "Hyundai HB20 Turbo Automático de baixa quilometragem (18.000 km). Cor exclusiva Azul Sapphire, agilidade incrível nas subidas de Juiz de Fora e conforto de um câmbio automático suave.",
    isFeatured: false,
    badge: "Seminovo",
    hasInspectionReport: true,
    singleOwner: true,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Ford",
    model: "Ka",
    version: "1.5 SE Plus 12V",
    yearFabrication: 2019,
    yearModel: 2020,
    price: "48900.00",
    fipePrice: "51200.00",
    mileage: 61000,
    fuel: "Flex",
    transmission: "Manual",
    color: "Vermelho Arpoador",
    bodyType: "Hatch",
    plateEnd: "3",
    doors: 4,
    coverImage: "/images/vehicles/ford-ka.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/ford-ka.jpg"
    ]),
    features: JSON.stringify([
      "Motor 1.5 Dragon de 136cv",
      "Central Multimídia Ford SYNC 2.5",
      "Sensor de estacionamento traseiro",
      "Ar-condicionado",
      "Direção elétrica leve",
      "Vidros elétricos dianteiros e traseiros",
      "Travas elétricas e alarme",
      "Faróis de neblina"
    ]),
    description: "Ford Ka 1.5 SE Plus com motor 3 cilindros de alta potência (136cv), perfeito para estrada e cidade. Carro muito bem conservado, revisado com garantia de loja de 1 ano motor e câmbio.",
    isFeatured: false,
    badge: "Oportunidade",
    hasInspectionReport: true,
    singleOwner: false,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Volkswagen",
    model: "T-Cross",
    version: "250 TSI Highline Automático",
    yearFabrication: 2021,
    yearModel: 2022,
    price: "110900.00",
    fipePrice: "114900.00",
    mileage: 35000,
    fuel: "Flex",
    transmission: "Automático",
    color: "Cinza Platinum",
    bodyType: "SUV",
    plateEnd: "7",
    doors: 4,
    coverImage: "/images/vehicles/vw-tcross.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/vw-tcross.jpg"
    ]),
    features: JSON.stringify([
      "Motor 1.4 TSI de 150cv com câmbio Tiptronic de 6 marchas",
      "Painel 100% digital Active Info Display 10,25\"",
      "Central multimídia VW Play de 10,1\"",
      "Teto solar panorâmico elétrico Sky View",
      "Bancos revestidos em couro bicolor",
      "Faróis Full LED com DRL integrado",
      "Carregador de smartphone por indução",
      "Park Assist (estacionamento automático autônomo)",
      "Sensor de fadiga do condutor e frenagem pós-colisão",
      "Rodas aro 17\" diamantadas exclusivas"
    ]),
    description: "T-Cross Highline versão topo de linha com teto solar panorâmico e painel digital! Um SUV moderno, seguro com 5 estrelas no Latin NCAP, com desempenho esportivo do motor 1.4 TSI.",
    isFeatured: true,
    badge: "Destaque",
    hasInspectionReport: true,
    singleOwner: true,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Chevrolet",
    model: "Tracker",
    version: "1.2 Turbo Premier Automático",
    yearFabrication: 2023,
    yearModel: 2023,
    price: "129900.00",
    fipePrice: "134200.00",
    mileage: 12000,
    fuel: "Flex",
    transmission: "Automático",
    color: "Branco Summit",
    bodyType: "SUV",
    plateEnd: "0",
    doors: 4,
    coverImage: "/images/vehicles/chevrolet-tracker.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/chevrolet-tracker.jpg"
    ]),
    features: JSON.stringify([
      "Motor 1.2 Turbo de 133cv com torque instantâneo",
      "Teto solar panorâmico elétrico",
      "Alerta de colisão frontal com frenagem autônoma de emergência",
      "Alerta de ponto cego nos retrovisores",
      "Sistema de estacionamento semiautônomo Easy Park",
      "Ar-condicionado digital",
      "Carregador de celular por indução",
      "Wi-Fi nativo e sistema OnStar 24 horas",
      "Faróis Full LED com projetor",
      "Bancos com acabamento premium e costuras em tom cobre"
    ]),
    description: "Tracker Premier 1.2 Turbo seminovo ano 2023 com apenas 12.000 km, garantia de fábrica ativa até 2026. Versão topo de linha com teto panorâmico, pacote completo de segurança e teto solar elétrico.",
    isFeatured: true,
    badge: "Garantia",
    hasInspectionReport: true,
    singleOwner: true,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "Renault",
    model: "Duster",
    version: "1.6 16V Iconic CVT",
    yearFabrication: 2022,
    yearModel: 2023,
    price: "89900.00",
    fipePrice: "93500.00",
    mileage: 28000,
    fuel: "Flex",
    transmission: "CVT",
    color: "Laranja Atacama",
    bodyType: "SUV",
    plateEnd: "8",
    doors: 4,
    coverImage: "/images/vehicles/renault-duster.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/renault-duster.jpg"
    ]),
    features: JSON.stringify([
      "Câmbio automático CVT Xtronic com 6 marchas simuladas",
      "Central Multimídia EasyLink 8\" com câmera Multiview 360°",
      "Alerta de ponto cego",
      "Sensor crepuscular",
      "Chave presencial em formato de cartão",
      "Porta-malas gigante de 475 litros",
      "Bancos com acabamento em couro",
      "Rodas diamantadas aro 17\"",
      "Ar-condicionado digital automático"
    ]),
    description: "Renault Duster Iconic com visual robusto e cor marcante Laranja Atacama. Porta-malas enorme, excelente altura do solo para enfrentar qualquer terreno em Juiz de Fora e região da Zona da Mata.",
    isFeatured: false,
    badge: "Seminovo",
    hasInspectionReport: true,
    singleOwner: true,
    ipvaPaid: true,
    status: "available",
  },
  {
    brand: "BMW",
    model: "320i",
    version: "2.0 Turbo GP ActiveFlex",
    yearFabrication: 2020,
    yearModel: 2021,
    price: "189900.00",
    fipePrice: "196000.00",
    mileage: 39000,
    fuel: "Flex",
    transmission: "Automático",
    color: "Azul Portimão",
    bodyType: "Sedan",
    plateEnd: "9",
    doors: 4,
    coverImage: "/images/vehicles/bmw-320i.jpg",
    gallery: JSON.stringify([
      "/images/vehicles/bmw-320i.jpg"
    ]),
    features: JSON.stringify([
      "Motor 2.0 TwinPower Turbo de 184cv e tração traseira",
      "Câmbio automático ZF de 8 velocidades com paddle shifts",
      "BMW Live Cockpit Professional com tela curva e GPS",
      "Assistente pessoal inteligente 'Hey BMW'",
      "Faróis Full LED com assistente de farol alto",
      "Bancos esportivos elétricos com memória para o motorista",
      "Ar-condicionado automático digital de 3 zonas",
      "Reversing Assistant (refaz os últimos 50m em marcha a ré autonomamente)",
      "Rodas de liga leve aro 18\" com pneus Run-Flat"
    ]),
    description: "BMW 320i G20 na belíssima cor Azul Portimão. O ápice do prazer de dirigir com tração traseira e acabamento refinado alemão. Procedência ímpar, todas revisões na concessionária autorizada.",
    isFeatured: true,
    badge: "Destaque",
    hasInspectionReport: true,
    singleOwner: true,
    ipvaPaid: true,
    status: "available",
  }
];

export const initialReviews = [
  {
    authorName: "Marcos Vinícius S.",
    neighborhood: "São Mateus, Juiz de Fora",
    rating: 5,
    comment: "Excelente atendimento da equipe da Modelo Multimarcas JF! Comprei meu Corolla e pegaram meu carro antigo na troca por uma avaliação muito justa. Documentação rápida e sem dor de cabeça.",
    purchasedVehicle: "Toyota Corolla XEi",
    isPublished: true,
  },
  {
    authorName: "Carla Oliveira Mendes",
    neighborhood: "Bom Pastor, Juiz de Fora",
    rating: 5,
    comment: "Atendimento impecável! O laudo cautelar me passou total segurança. Carro entregue polido, cheiroso e com todas as revisões comprovadas. Super recomendo a loja na Rio Branco!",
    purchasedVehicle: "Chevrolet Onix Turbo",
    isPublished: true,
  },
  {
    authorName: "Rodrigo Alvim",
    neighborhood: "Cascatinha, Juiz de Fora",
    rating: 5,
    comment: "Financiamento aprovado em menos de 30 minutos com taxas excelentes pelo Santander. Parabéns pelo profissionalismo e transparência em cada detalhe.",
    purchasedVehicle: "Jeep Renegade Sport",
    isPublished: true,
  },
  {
    authorName: "Fernanda Toledo",
    neighborhood: "Granbery, Juiz de Fora",
    rating: 5,
    comment: "Comprei meu primeiro seminovo aqui e foi a melhor experiência possível. Vendedor atencioso, tirou todas as dúvidas e me mandou vídeo detalhado do carro antes da visita.",
    purchasedVehicle: "Fiat Argo Drive",
    isPublished: true,
  },
  {
    authorName: "Leandro Guimarães",
    neighborhood: "Benfica, Juiz de Fora",
    rating: 5,
    comment: "Estoque de altíssimo nível. Carros selecionados a dedo mesmo, sem maquiagem. Valeu muito a pena sair da zona norte para fechar negócio com a Modelo Multimarcas JF.",
    purchasedVehicle: "Volkswagen T-Cross Highline",
    isPublished: true,
  }
];

export async function seedDatabase(force = false) {
  try {
    const existingVehicles = await db.select({ count: count() }).from(vehicles);
    const vehicleCount = Number(existingVehicles[0]?.count ?? 0);

    if (vehicleCount === 0 || force) {
      if (force) {
        await db.delete(leads);
        await db.delete(testDrives);
        await db.delete(appraisals);
        await db.delete(reviews);
        await db.delete(vehicles);
      }

      for (const item of initialVehicles) {
        await db.insert(vehicles).values(item);
      }

      for (const r of initialReviews) {
        await db.insert(reviews).values(r);
      }

      // Sample initial lead and test drive
      await db.insert(leads).values({
        vehicleName: "Chevrolet Onix 1.0 Turbo LT",
        name: "Guilherme Ferreira",
        phone: "(32) 99876-5432",
        email: "guilherme.jf@email.com",
        leadType: "financing",
        message: "Gostaria de simular entrada de R$ 20.000 em 48x para o Onix Turbo.",
        entryAmount: "20000.00",
        installments: 48,
        status: "new",
        notes: "Cliente tem score bom, preferência por financiamento BV ou Santander.",
      });

      await db.insert(testDrives).values({
        vehicleName: "Jeep Renegade 1.8 Flex Sport",
        customerName: "Patrícia Nogueira",
        customerPhone: "(32) 99123-4567",
        customerEmail: "patricia.adv@email.com",
        preferredDate: "2025-05-15",
        preferredTime: "14:30",
        locationPreference: "dealership",
        notes: "Prefere testar o carro na subida do Cascatinha/Teixeiras.",
        status: "pending",
      });

      await db.insert(appraisals).values({
        customerName: "Felipe Bastos",
        customerPhone: "(32) 98844-3322",
        customerEmail: "felipe.bastos@email.com",
        tradeBrand: "Renault",
        tradeModel: "Sandero Stepway",
        tradeYear: 2018,
        tradeMileage: 64000,
        tradeTransmission: "Manual",
        tradeFuel: "Flex",
        tradeColor: "Prata",
        tradeCondition: "Excelente",
        hasFinancing: false,
        interestedVehicleName: "Toyota Corolla 2.0 XEi",
        notes: "Carro quitado com IPVA 2026 pago e 4 pneus novos.",
        estimatedValue: "44000.00",
        status: "pending",
      });

      console.log("Database seeded successfully with initial dealership data.");
    }
  } catch (error) {
    console.error("Error seeding database:", error);
  }
}
